import "./globals.css";
import { Geist } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const geist = Geist({
  subsets: ["latin"],
  weight: ["400", "700"],
  display:'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geist.className}>{children}</body>
    </html>
  );
}
